### Numpy Indexing and Selection

In [3]:
import numpy as np

In [7]:
arr = np.arange(0,11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr [1:5]

array([1, 2, 3, 4])

In [15]:
arr [0:7] 

array([0, 1, 2, 3, 4, 5, 6])

Getting everything in the array from the beginning to index 6

In [22]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

Similary getting everything in an array from a certain index can be done by using the same slice notation

In [24]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [27]:
arr[0:5]=100

Braodcasting

In [29]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

Reseting the array

In [32]:
arr =np.arange(0,11)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
slice_of_arr = arr [0:6]


In [41]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

Broadcasting on the array above

In [48]:
slice_of_arr[:] = 99

In [50]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [54]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied to avoid memroy issues with large arrays copies can be made like below.

In [59]:
arr_copy = arr.copy()

In [63]:
arr_copy[:]= 100

In [65]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [67]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

So if you look up broadcasting the copy of the array does not affect the original array

### Indexing a 2D array

In [73]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [75]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
Getting Values from a 2D array can be done using double square brakets [][]

In [90]:
arr_2d[2][1]

40

Getting these values can also be done using single square brakets [,] with a comma e.g [1.1]

In [100]:
arr_2d[2,1]

40

If you want a section (Sub section) of elements as opposed to only one element, You can use slice notation

In [119]:
arr_2d[:2,2:]

array([[15],
       [30]])

Extra methods of selection

In [123]:
arr_new= np.arange(1,11)

In [130]:
arr_new

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can take the array above and combine it with comparison operators to get a full boolean out of

In [140]:
bool_arr_new=arr_new>5

In [142]:
bool_arr_new

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

To get only the values that are true in the array we can add the bool_arr_new in the square brakets

In [156]:
arr_new [bool_arr_new]

array([ 6,  7,  8,  9, 10])

The above can also be done in one go as opposed to the example above. See different exmple but similer answer below

In [164]:
arr_new[arr_new>5]

array([ 6,  7,  8,  9, 10])

Now for example we want all the elements in the array "arr_new" that are less then 5

In [170]:
arr_new[arr_new<3]

array([1, 2])

In [179]:
arr_2d1 = np.arange(50).reshape(5,10)

In [181]:
arr_2d1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [210]:
arr_2d1[3:5,1:3]

array([[31, 32],
       [41, 42]])