### Numpy Operations

- Array with Array
- Array with Scalars
- Universal Array Function

In [5]:
import numpy as np

In [7]:
arr = np.arange(0,11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

We can easily perform array with array operations just by using simple operations sighns that we are alreay used to from python itself

### For Example if you want to add two Arrays 
Given that we have created an array arr above we can add two arrays (arr) like below

In [14]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

The same thing can be done for subtraction

In [17]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

The same thing can also be done for multiplication

In [20]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

Arrays with scalar operations can also be performed in the same manner

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Lets say I wanted to add 20 to each number in the array above. That can be done as below.

In [27]:
arr + 20

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

Now this works exactly the same way for other operations with scalars such as Subtraction,multiplication, division etc

In [30]:
arr - 20

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10])

In [32]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

Unlike python that gives you an error when you divide 0 by 0 numpy does not give you an error but rather a warning message.

The example below the first elemet in the array is 0 and dividing 0/0 using numpy gives the warning message below and an answer of nan

In [42]:
arr / arr


C:\Users\Matt\AppData\Local\Temp\ipykernel_12400\2811617162.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [47]:
1/0

ZeroDivisionError: division by zero

In [49]:
arr / 0

C:\Users\Matt\AppData\Local\Temp\ipykernel_12400\3942562399.py:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0
C:\Users\Matt\AppData\Local\Temp\ipykernel_12400\3942562399.py:1: RuntimeWarning: invalid value encountered in divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [53]:
1 / arr

C:\Users\Matt\AppData\Local\Temp\ipykernel_12400\1528351372.py:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

### Exponants on Arrays

In [57]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### Universal Array Function

- The Square root of all elements in an array. # np.sqrt()
- Calculating the exponantial # np.exp()
- Maximum # np.max()
- Trigonometirc functions
  - np.sin()
  - np.log()
    


In [62]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [67]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [71]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [75]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [77]:
np.log(arr)

C:\Users\Matt\AppData\Local\Temp\ipykernel_12400\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])