### Numpy Arrays
There two types, the first one is the vectors(1dimentional) the other is the matrices (2 Dimentional)

Installing numpy

In [20]:
!pip install numpy

### Using Numpy

In [29]:
import numpy as np

In [7]:
my_list =[1,2,3]

### Casting a normal list to an array

In [33]:
my_list

[1, 2, 3]

In [35]:
arr = np.array(my_list)

In [37]:
arr

array([1, 2, 3])

### Two Dimentional Array

In [41]:
my_mat =[[1,2,3,],[4,5,6],[7,8,9]]

In [43]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [45]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

Generating an array of all zeros

In [60]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [68]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

The same can be done for 1nes 

In [73]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [77]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

Creating an Identity Matrix

In [94]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Creating Random numbers from 0 to 1

In [109]:
np.random.rand(3)

array([0.56584342, 0.03503675, 0.23794128])

In [121]:
np.random.rand(3,3)

array([[0.82828497, 0.62131219, 0.54764323],
       [0.37592476, 0.08344493, 0.01919597],
       [0.45538461, 0.05997063, 0.87843968]])

Creating Random numbers from 0 to n

In [124]:
np.random.randn(2)

array([-0.17707054, -0.83008892])

In [126]:
np.random.randn(2,2)

array([[ 0.44051872,  0.40663975],
       [-1.27038476,  0.67701851]])

Creating Random numbers from n to n

In [134]:
np.random.randint(1,100)

64

If for example you need 5 random integers between 1 and 100 (1 inclusive but 100 excluded):

In [141]:
np.random.randint(1,100,5)

array([28, 16, 63, 97,  6])

In [144]:
arr = np.arange(25)

In [146]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [148]:
ranarr = np.random.randint(0,50,10)

In [150]:
ranarr

array([22,  6, 18,  3, 10, 10, 16, 40, 22, 35])

### Reshape method:
make sure the number of rows times the number of colums equals the digits you have RXC=Number of elements

In [160]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [166]:
ranarr.max()

40

In [175]:
ranarr

array([22,  6, 18,  3, 10, 10, 16, 40, 22, 35])

In [177]:
ranarr.argmax()

7

In [179]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [181]:
arr.shape

(25,)

In [192]:
arr.dtype

dtype('int32')

In [194]:
from numpy.random import randint

In [196]:
randint(2,10)

8